language: node_js

node_js:
  - stable

addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - npm install

script:
  - npm run test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls